### PR TITLE
Save event meta if classic editor plugin and gutenberg option are enabled

### PR DESCRIPTION
**Pull request by mitogh**
Make sure events meta data is saved if the classic editor plugin is enabled
and if the gutenberg blocks for events are enabled.

Ticket: https://central.tri.be/issues/121267

### CODE REVIEW

**Comment by mitogh** [comment]
This PR requires: 

- https://github.com/moderntribe/tribe-common/pull/1067

In order to pass the tests as the new filter is located on the latest of `common`

**Comment by bordoni** [comment]
Same here, tests failing.

**Comment by mitogh** [comment]
In this one is expected due `common` does not have the filter to pass the tests, let me update this branch with the latest version of `common`

**Comment by mitogh** [comment]
Test is fixed on: 

- https://github.com/moderntribe/the-events-calendar/pull/2590

**Pull request merged**
