### PR TITLE
Add event ID parameter to tribe_events_event_classes filter

### PR DESCRIPTION
**Pull request by niconerd**
https://central.tri.be/issues/64807

### CODE REVIEW

**Comment by niconerd** [comment]
@bordoni qq I just found this filter is being used here: https://github.com/moderntribe/the-events-calendar/blob/master/src/Tribe/Template_Factory.php#L105 and here https://github.com/moderntribe/the-events-calendar/blob/master/src/Tribe/Template_Factory.php#L460

Do you think those uses need amend? Or maybe we should roll back the change I made?

**Comment by mitogh** [comment]
I think this is fine @niconerd as the filter call the method `event_classes` with only one argument the `$classes`.

By default `apply_filters` only send a single argument if you have multiple arguments in a filter when you use the filter you need to specify how many arguments do you need if non specified only one is passed.

So it should be fine

**Comment by mitogh** [comment]
Let me know if there's anything else I can do for you @niconerd

**Comment by niconerd** [comment]
Thanks for reviewing Cris 🥇

**Pull request merged**
