### PR TITLE
fix feed rewrite rule typo

### PR DESCRIPTION
**Pull request by aaemnnosttv**
This single-line change pull request is a simple fix of a type for the rewrite rule for the main events feed.

### CODE REVIEW

**Comment by aaemnnosttv** [comment]
Just brought this up to date with the latest on `develop`.

**Comment by zbtirrell** [comment]
Logged in Central as ticket #33913.

**Comment by zbtirrell** [comment]
@aaemnnosttv we did a big restructure of our files today.  Can you refresh this pull request and we'll get this into the current release?

**Comment by zbtirrell** [comment]
thanks!

**Pull request merged**
