### PR TITLE
Add tribe_events_month_get_events_in_month hook in Tribe__Events__Template__Month::set_events_in_month()

### PR DESCRIPTION
**Pull request by sc0ttkclark**
https://central.tri.be/issues/83317

Needed in next MR please.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Where do I add it for this MR? I don't see a new version listed in https://github.com/moderntribe/the-events-calendar/blob/feature/83317-add-events-in-month-filter/readme.txt

**Comment by barryhughes** [comment]
[Right here](https://github.com/moderntribe/the-events-calendar/blob/release/M17.14/readme.txt#L330-L334) :smile: ... could be you need to pull the latest release branch commits into your own branch

**Comment by sc0ttkclark** [comment]
Doh

**Comment by sc0ttkclark** [comment]
Proposed changelog entry:

```
* Tweak - Added tribe_events_month_get_events_in_month filter to allow overriding of events used in month templates. [83317]
```

**Comment by barryhughes** [comment]
Right on, that works (pre-emptively tagging for merge - if you can add that changelog entry first though that would be A1)

**Pull request merged**
