### PR TITLE
#112432 Remove References to Facebook from EA

### PR DESCRIPTION
**Pull request by ggwicz**
**Ticket:** [**⌗112432**](http://central.tri.be/issues/112432)

The scope of this change is quite large, but I don't think I've misunderstood it. **The goal here is to remove all UI referencing Facebook as an import origin in Event Aggregator.** Commensurate with this is the removal of a bunch of the related "plumbing" that itself is no longer being used.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Space found before comma in function call | [Migrate.php:309](https://github.com/moderntribe/the-events-calendar/blob/cbdb50319ec09f979262ccea6c1d6a08ffcc2d86/src/Tribe/Aggregator/Migrate.php#L309)
:x: | Expected 1 space after comma in function call; 2 found | [Migrate.php:310](https://github.com/moderntribe/the-events-calendar/blob/cbdb50319ec09f979262ccea6c1d6a08ffcc2d86/src/Tribe/Aggregator/Migrate.php#L310)
:warning: | Comment refers to a TODO task | [New.php:611](https://github.com/moderntribe/the-events-calendar/blob/cbdb50319ec09f979262ccea6c1d6a08ffcc2d86/src/Tribe/Aggregator/Tabs/New.php#L611)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Space found before comma in function call | [Migrate.php:312](https://github.com/moderntribe/the-events-calendar/blob/0fc1425bfb9fe50caea53dbfe0db9757eca692c6/src/Tribe/Aggregator/Migrate.php#L312)
:x: | Expected 1 space after comma in function call; 2 found | [Migrate.php:313](https://github.com/moderntribe/the-events-calendar/blob/0fc1425bfb9fe50caea53dbfe0db9757eca692c6/src/Tribe/Aggregator/Migrate.php#L313)
:warning: | Comment refers to a TODO task | [New.php:611](https://github.com/moderntribe/the-events-calendar/blob/0fc1425bfb9fe50caea53dbfe0db9757eca692c6/src/Tribe/Aggregator/Tabs/New.php#L611)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
Make sure tests pass, and go for it.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [New.php:611](https://github.com/moderntribe/the-events-calendar/blob/7d0923d86891e0878a4e40f4a3d48600c5862768/src/Tribe/Aggregator/Tabs/New.php#L611)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [New.php:611](https://github.com/moderntribe/the-events-calendar/blob/02e460a66e6f949e520c9c48c7d22979a06986c1/src/Tribe/Aggregator/Tabs/New.php#L611)

> via jenkins/codesniffer-phpcs

**Comment by ggwicz** [comment]
Tests are now passing; the codesniffer flag is just for a `@todo` comment in the code that I don't think it's worth removing for now.

@bordoni (or others), mind giving this another quick review to make sure my methods of making tests pass here is kosher? My methods were to:

1. remove a cleanup task that is now unnecessary 
2. mark a number of tests that call deprecated FB classes and methods as `markTestSkipped`

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [New.php:611](https://github.com/moderntribe/the-events-calendar/blob/c5f3faaf189b4706e76cad81384cea7a6038f380/src/Tribe/Aggregator/Tabs/New.php#L611)

> via jenkins/codesniffer-phpcs

**Comment by ggwicz** [comment]
After confirming on dev scrum today, I've just gone ahead and removed the FB tests outright since FB support is totally annihilated. 💀 This is ready for a quick Code Review again and can merge as long as that is approved and that tests pass.

**Pull request merged**
