### PR TITLE
Cherry pick EA code from MR

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/113619

This PR cherry-picks the updates to EA import related codes from the MR code.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [Queue_Control.php:37](https://github.com/moderntribe/the-events-calendar/blob/d261dc321bdff471134c0b97d512f7ce62f1c7da/src/Tribe/Aggregator/Processes/Queue_Control.php#L37)
:warning: | The method parameter $return_id is never used | [Batch.php:44](https://github.com/moderntribe/the-events-calendar/blob/d261dc321bdff471134c0b97d512f7ce62f1c7da/src/Tribe/Aggregator/REST/V1/Endpoints/Batch.php#L44)
:warning: | The method parameter $return_id is never used | [State.php:15](https://github.com/moderntribe/the-events-calendar/blob/d261dc321bdff471134c0b97d512f7ce62f1c7da/src/Tribe/Aggregator/REST/V1/Endpoints/State.php#L15)
:warning: | Comment refers to a TODO task &quot;let's revisit this to return when more UI is exposed&quot; | [Abstract.php:1243](https://github.com/moderntribe/the-events-calendar/blob/d261dc321bdff471134c0b97d512f7ce62f1c7da/src/Tribe/Aggregator/Record/Abstract.php#L1243)
:warning: | The method parameter $batch_size is never used | [Async_Queue.php:189](https://github.com/moderntribe/the-events-calendar/blob/d261dc321bdff471134c0b97d512f7ce62f1c7da/src/Tribe/Aggregator/Record/Async_Queue.php#L189)
:warning: | The method parameter $ignored is never used | [CSV.php:119](https://github.com/moderntribe/the-events-calendar/blob/d261dc321bdff471134c0b97d512f7ce62f1c7da/src/Tribe/Aggregator/Record/CSV.php#L119)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [Queue_Control.php:37](https://github.com/moderntribe/the-events-calendar/blob/ea26de7a6e957bbd3ebff09b9101065a9aecead6/src/Tribe/Aggregator/Processes/Queue_Control.php#L37)
:warning: | The method parameter $return_id is never used | [Batch.php:44](https://github.com/moderntribe/the-events-calendar/blob/ea26de7a6e957bbd3ebff09b9101065a9aecead6/src/Tribe/Aggregator/REST/V1/Endpoints/Batch.php#L44)
:warning: | The method parameter $return_id is never used | [State.php:15](https://github.com/moderntribe/the-events-calendar/blob/ea26de7a6e957bbd3ebff09b9101065a9aecead6/src/Tribe/Aggregator/REST/V1/Endpoints/State.php#L15)
:warning: | Comment refers to a TODO task &quot;let's revisit this to return when more UI is exposed&quot; | [Abstract.php:1243](https://github.com/moderntribe/the-events-calendar/blob/ea26de7a6e957bbd3ebff09b9101065a9aecead6/src/Tribe/Aggregator/Record/Abstract.php#L1243)
:warning: | The method parameter $batch_size is never used | [Async_Queue.php:189](https://github.com/moderntribe/the-events-calendar/blob/ea26de7a6e957bbd3ebff09b9101065a9aecead6/src/Tribe/Aggregator/Record/Async_Queue.php#L189)
:warning: | The method parameter $ignored is never used | [CSV.php:119](https://github.com/moderntribe/the-events-calendar/blob/ea26de7a6e957bbd3ebff09b9101065a9aecead6/src/Tribe/Aggregator/Record/CSV.php#L119)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
The sniffer issues are from the branch and can be safely ignored (but feel free to take a look!)

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | die must follow wp_redirect | [Queue_Control.php:37](https://github.com/moderntribe/the-events-calendar/blob/ffc785656d998af1993d5f4569e64c4a0b73c523/src/Tribe/Aggregator/Processes/Queue_Control.php#L37)
:warning: | The method parameter $return_id is never used | [Batch.php:44](https://github.com/moderntribe/the-events-calendar/blob/ffc785656d998af1993d5f4569e64c4a0b73c523/src/Tribe/Aggregator/REST/V1/Endpoints/Batch.php#L44)
:warning: | The method parameter $return_id is never used | [State.php:15](https://github.com/moderntribe/the-events-calendar/blob/ffc785656d998af1993d5f4569e64c4a0b73c523/src/Tribe/Aggregator/REST/V1/Endpoints/State.php#L15)
:warning: | Comment refers to a TODO task &quot;let's revisit this to return when more UI is exposed&quot; | [Abstract.php:1243](https://github.com/moderntribe/the-events-calendar/blob/ffc785656d998af1993d5f4569e64c4a0b73c523/src/Tribe/Aggregator/Record/Abstract.php#L1243)
:warning: | The method parameter $batch_size is never used | [Async_Queue.php:189](https://github.com/moderntribe/the-events-calendar/blob/ffc785656d998af1993d5f4569e64c4a0b73c523/src/Tribe/Aggregator/Record/Async_Queue.php#L189)
:warning: | The method parameter $ignored is never used | [CSV.php:119](https://github.com/moderntribe/the-events-calendar/blob/ffc785656d998af1993d5f4569e64c4a0b73c523/src/Tribe/Aggregator/Record/CSV.php#L119)

> via jenkins/codesniffer-phpcs

**Pull request merged**
