### PR TITLE
Restore Travis CI tests to working order

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: n/a yet

### CODE REVIEW

**Comment by lucatume** [comment]
@borkweb I'm kinda lost here: https://travis-ci.org/moderntribe/the-events-calendar/jobs/287493415 I've ported over the submodule handling logic but that seems to fool me. Stranger is, though, that it [initially worked](https://travis-ci.org/moderntribe/the-events-calendar/jobs/287454774).
Do you have any idea? Feel free to hack this PR.

**Comment by bordoni** [comment]
`git submodule update --init --recursive --remote` might do the job. It's that the Submodule doesn't have that specific Hash, it happens with Tags a lot.

**Comment by lucatume** [comment]
That did not make it... mmm. Will tinker with this more.

**Comment by barryhughes** [comment]
Updating base branch: release/M17.20 has shipped.

**Comment by barryhughes** [comment]
This was closed automatically when we shutdown release/M17.21 - reopening but targeting release/M17.22.

**Pull request closed without merging**
