### PR TITLE
Remove vendor/tickets

### PR DESCRIPTION
**Pull request by barryhughes**
It was fun, but every dog has its day.

https://central.tri.be/issues/71908

### CODE REVIEW

**Comment by bordoni** [comment]
👍

**Comment by zbtirrell** [comment]
Doing this in a maintenance release feels a bit risky to me, but, I trust Barry if he's thought it through

**Comment by barryhughes** [comment]
As discussed, let's hold on this one.

**Comment by tr1b0t** [comment]
:bangbang: This Pull Request is against a Central ticket for "To Be Determined". It shouldn't be merged until the Central ticket has been changed to "Current Release" or "CR Maintenance Release".

**Comment by bordoni** [comment]
Im closing this puppy because there are more commits here.

**Pull request closed without merging**
