### PR TITLE
Msg for Empty field on event post - with merge conflicts fixed

### PR DESCRIPTION
**Pull request by borkweb**
This is a finalization of the [PR](https://github.com/moderntribe/the-events-calendar/pull/306) by @tapan29bd! Thank you!

> In the Add New Event, if I keep the Event name meta box empty and press Tab then it shows "Event Name Already Exist" which is ambiguous. I fixed this with a "Evant name Can Not be Empty" msg.
> 
> Signed-off-by: Tapan Kumer Das <tapan@innovativebd.net>
> 
> Internal reference: https://central.tri.be/issues/40223

### CODE REVIEW

**Comment by tapan29bd** [comment]
@borkweb I am glad that my contribution is merge :+1:

**Comment by borkweb** [comment]
Me too! Thank you for the fix :) It'll make it into our next major release!

**Comment by tapan29bd** [comment]
But the sad thing is, I don't see me in the contributor list :(

**Comment by zbtirrell** [comment]
I see you as contributor here:
screen shot 2015-10-13 at 1 55 28 pm

**Comment by tapan29bd** [comment]
@zbtirrell hahaha... yeah you are right. But not in here, https://github.com/moderntribe/the-events-calendar/graphs/contributors
Anyway, still it feels good that my contribution helps :+1:

**Comment by borkweb** [comment]
Oh weird. Those stats are probably refreshed periodically!

**Comment by tapan29bd** [comment]
@borkweb I dont think so, Its something else. I think, this is because you opened this PR as you get merge conflict in my PR. After fixing the conflict you merge this PR so system can't recognize my PR. And that's why its not listed my name as contributor. Anyway no problem :-)

**Pull request merged**
