### PR TITLE
Fix WPML old and new incompatibilities

### PR DESCRIPTION
**Pull request by lucatume**
Tickets:
* https://central.tri.be/issues/70520
* https://central.tri.be/issues/70522

Smaller fixes on not listed and strange WPML issues. I've checked PRO code too (our other plugin with explicit WPML integration) and it's ok.

### CODE REVIEW

**Comment by tr1b0t** [comment]
:bangbang: This Pull Request is against a Central ticket for "To Be Determined". It shouldn't be merged until the Central ticket has been changed to "Current Release" or "CR Maintenance Release".

**Comment by bordoni** [comment]
👍

**Comment by lucatume** [comment]
Thanks @bordoni! Will wait on word by Zach to know if this has to go in or wait.

**Comment by lucatume** [comment]
I've refreshed this branch to merge latest `develop`; it addresses WPML compatibility issues with changed/removed code. Probably good for MR?

**Comment by bordoni** [comment]
Go for it!

**Pull request merged**
