### PR TITLE
Add context to string "All %s"

### PR DESCRIPTION
**Pull request by pedro-mendonca**
This will allow different translations and result depending on context:
All (XX) [Event count]
All Events [plural label]

[#64586](https://central.tri.be/issues/64586)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$events_label_plural' | [single-event.php:27](https://github.com/moderntribe/the-events-calendar/blob/228d8e851d8e443c5a6f575d03c52ae6f4189973/src/views/single-event.php#L27)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$events_label_plural' | [single-event.php:27](https://github.com/moderntribe/the-events-calendar/blob/228d8e851d8e443c5a6f575d03c52ae6f4189973/src/views/single-event.php#L27)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
Thanks, @pedro-mendonca - and apologies for the delay in processing this. This looks like a valid change and we'll see about merging it in shortly :+1: 

(Ticketed: [#64586](https://central.tri.be/issues/64586))

**Comment by pedro-mendonca** [comment]
Thank you :+1:

**Pull request merged**
