### PR TITLE
Show the help page on network admin

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/68665

Builds on: https://github.com/moderntribe/tribe-common/pull/250

This PR adds a link in the network admin to show the help page.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space before the last parenthesis | [Aggregator.php:155](https://github.com/moderntribe/the-events-calendar/blob/d23818f77b8338869f20d060c07bd47ebb8a9b01/src/Tribe/Aggregator.php#L155)
:x: | There must be a single space before the last parenthesis | [Aggregator.php:158](https://github.com/moderntribe/the-events-calendar/blob/d23818f77b8338869f20d060c07bd47ebb8a9b01/src/Tribe/Aggregator.php#L158)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [status.php:181](https://github.com/moderntribe/the-events-calendar/blob/d23818f77b8338869f20d060c07bd47ebb8a9b01/src/admin-views/aggregator/status.php#L181)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$notes' | [status.php:185](https://github.com/moderntribe/the-events-calendar/blob/d23818f77b8338869f20d060c07bd47ebb8a9b01/src/admin-views/aggregator/status.php#L185)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [status.php:203](https://github.com/moderntribe/the-events-calendar/blob/d23818f77b8338869f20d060c07bd47ebb8a9b01/src/admin-views/aggregator/status.php#L203)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$notes' | [status.php:207](https://github.com/moderntribe/the-events-calendar/blob/d23818f77b8338869f20d060c07bd47ebb8a9b01/src/admin-views/aggregator/status.php#L207)
:x: | A closing tag is not permitted at the end of a PHP file | [status.php:211](https://github.com/moderntribe/the-events-calendar/blob/d23818f77b8338869f20d060c07bd47ebb8a9b01/src/admin-views/aggregator/status.php#L211)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
:spiral_notepad: changelog entry?

**Comment by lucatume** [comment]
There it is.

**Comment by barryhughes** [comment]
:+1:

**Pull request merged**
