### PR TITLE
Make sure we have the correct version of wp-browser

### PR DESCRIPTION
**Pull request by bordoni**
Based on the documentation of `wp-browser` we need to remove the dependency for `Codeception\Command\DbSnapshot` if we go to version `wp-browser@2.2.0` 

---

If we stick to version `2.1.6` we could keep using `DbSnapshot` and that could be a faster solution.

### CODE REVIEW

**Comment by lucatume** [comment]
Same here as per https://github.com/moderntribe/events-pro/pull/1102: why not remove DBSnapshot and setup commands and use wp-browser `2.2.0`?

**Comment by lucatume** [comment]
Since tests are passing go on.

**Comment by bordoni** [comment]
Should we add the lock time here too? `10s` that you added for *Events Pro*

**Comment by lucatume** [comment]
> Should we add the lock time here too? `10s` that you added for _Events Pro_

Yep, it would not hurt at all.

**Pull request merged**
