### PR TITLE
Adding data filter

### PR DESCRIPTION
**Pull request by mwender**
Adds a filter for modifying the data returned by a REST API call for a single event (e.g. `wp-json/tribe/events/v1/events/[eventId]`).

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Whitespace found at end of line | [Single_Event.php:67](https://github.com/moderntribe/the-events-calendar/blob/a00f1663a2ed66cb8938a4cb260e73820353c9b9/src/Tribe/REST/V1/Endpoints/Single_Event.php#L67)
:x: | Whitespace found at end of line | [Single_Event.php:74](https://github.com/moderntribe/the-events-calendar/blob/a00f1663a2ed66cb8938a4cb260e73820353c9b9/src/Tribe/REST/V1/Endpoints/Single_Event.php#L74)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
Hi @mwender,

could you take care to remove the excess white space the bot reported?

**Comment by lucatume** [comment]
This issue has been ticketed at https://central.tri.be/issues/88748

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Whitespace found at end of line | [Single_Event.php:76](https://github.com/moderntribe/the-events-calendar/blob/8cbc7cae7893454fd3ec15ce7a0cf7e5b5cb4d53/src/Tribe/REST/V1/Endpoints/Single_Event.php#L76)

> via jenkins/codesniffer-phpcs

**Pull request merged**
