### PR TITLE
Feature/codeception test setup

### PR DESCRIPTION
**Pull request by lucatume**
I've set up the compser.json file and some accessory files, including a tests.md file, to scaffold some basic tests. At this point the tests already present in the the repo are not all working (I mean work, not pass) and the service ones will require more attention to have them up and running.

### CODE REVIEW

**Comment by bordoni** [comment]
Code Review?

**Comment by lucatume** [comment]
I've updated the code to make all the tests properly run.
"Run" means they do not throw errors and not that those are passing: about half of them are failing in fact.
What could be worth discussing is:

* moved the root test folder from `tests/codeception` to `tests` to stick with standards
* pushing a frozen test repository (I'm against it) for the sake of an easier use or pushing a semi-complete test environment that will require little customization work on the pulling developer side (actual, see `tests.md` file)

**Comment by borkweb** [comment]
I tried out the branch and wasn't as successful. I ran through the steps in `tests.md` (though I needed to use `vendor/bin/wpcept bootstrap:pyramid` and `vendor/codeception/codeception/codecept run`.

When I execute the `codecept run` step, I receive:

```
Fatal error: Class 'Codeception\Exception\ModuleException' not found in /private/var/www/events/wp-content/plugins/the-events-calendar/vendor/lucatume/wp-browser/src/WPDb.php on line 67
```

**Comment by lucatume** [comment]
I've updated the tests to work, many fail but still work.
Right now this branch means little but wanted to update on it. Pulling this branch and following the tests.md file through will yield working tests.

**Comment by lucatume** [comment]
Closing this PR as I've opened a new and updated one in https://github.com/moderntribe/the-events-calendar/pull/303

**Pull request closed without merging**
