### PR TITLE
Add events/by-slug/{slug} endpoint based on event single endpoint

### PR DESCRIPTION
**Pull request by sc0ttkclark**
https://central.tri.be/issues/92825

Enables looking up events by slug, same functionality as event single endpoint. With tests!

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [Inactive_Events.php:259](https://github.com/moderntribe/the-events-calendar/blob/3d32817ce5014c9f334f75af05c6819407912e82/src/Tribe/Inactive_Events.php#L259)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this' | [Inactive_Events.php:260](https://github.com/moderntribe/the-events-calendar/blob/3d32817ce5014c9f334f75af05c6819407912e82/src/Tribe/Inactive_Events.php#L260)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [column-categories.php:4](https://github.com/moderntribe/the-events-calendar/blob/3d32817ce5014c9f334f75af05c6819407912e82/src/admin-views/list/column-categories.php#L4)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [column-end-date.php:2](https://github.com/moderntribe/the-events-calendar/blob/3d32817ce5014c9f334f75af05c6819407912e82/src/admin-views/list/column-end-date.php#L2)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [column-start-date.php:2](https://github.com/moderntribe/the-events-calendar/blob/3d32817ce5014c9f334f75af05c6819407912e82/src/admin-views/list/column-start-date.php#L2)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this' | [view-link.php:5](https://github.com/moderntribe/the-events-calendar/blob/3d32817ce5014c9f334f75af05c6819407912e82/src/admin-views/list/view-link.php#L5)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [date-time.php:75](https://github.com/moderntribe/the-events-calendar/blob/3d32817ce5014c9f334f75af05c6819407912e82/src/admin-views/metabox/date-time.php#L75)

> via jenkins/codesniffer-phpcs

**Comment by sc0ttkclark** [comment]
Wow thanks @bordoni!

**Comment by barryhughes** [comment]
@sc0ttkclark should we add documentation to `Tribe__Events__REST__V1__Documentation__Event_Definition_Provider::get_documentation()` for this change?

**Comment by sc0ttkclark** [comment]
Good idea, I need to figure out how best to update that to reflect the different param for the endpoint using slug vs id.

**Comment by sc0ttkclark** [comment]
Yes, but please hold for now. I'm about to add the slug to the Event response (and the response doc you mentioned before) because of course we need the slug in the event data to be able to work with the slug in the endpoint paths :)

**Comment by sc0ttkclark** [comment]
Added changelog and updated the PR with `slug` in Event responses + `slug` allowed in Event insert/update

**Comment by barryhughes** [comment]
Clearing needs release flag, looks like this is all set to merge into `release/M17.25` :-)

cc @sc0ttkclark

**Pull request merged**
