### PR TITLE
Add note about PhantomJS to test instrucs (spotfix)

### PR DESCRIPTION
**Pull request by barryhughes**
Apart from some whitespace tidies, just adds a note about PhantomJS to steer folks in the right direction (lines 50-55).

### CODE REVIEW

**Comment by bordoni** [comment]
Should we add this to all the add-ons?

**Comment by barryhughes** [comment]
Hmm, all public ones maybe? Figured I'd start here and maybe longer term we'll eliminate the step to manually start it (phantomjs, I mean).

**Comment by bordoni** [comment]
I mean, we internally need to be running these tests, so I guess it would be a good call to remove that step ASAP or Add that on all the add-ons. But for sure on the public ones is nice first move.

**Comment by barryhughes** [comment]
Def :+1:

**Pull request merged**
