### PR TITLE
Fixed incorrect url path

### PR DESCRIPTION
**Pull request by andrasguseo**
https://central.tri.be/issues/95348

### CODE REVIEW

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for **, but this was pull requested against *release/M17.25*.

**Comment by lucatume** [comment]
Add a changelog entry?

**Comment by lucatume** [comment]
Needs files to be recompiled; navigate to `the-events-calendar` root folder and run:
```shell
npm install
gulp
```

If you get an error while running the `gulp` command then manually delete the `node_modules/gulp-git/node_modules` folder and run the `gulp` command again.

**Comment by bordoni** [comment]
Just as side note; I fixed that `gulp-git` On taskmaster

**Comment by barryhughes** [comment]
Recompiled,  changelog added: merging on Andras's behalf. Thanks for the fix, @andrasguseo!

**Pull request merged**
