### PR TITLE
Show the available Tickets on Listview

### PR DESCRIPTION
**Pull request by masteradhoc**
Credit to https://gist.github.com/ggwicz
https://gist.github.com/ggwicz/bb71d468a8139b1918e830ea302bc7af

### CODE REVIEW

**Comment by masteradhoc** [comment]
hi there. thanks for checking this PR. If its fine i'll add this also to the other views.

Uservoice:
https://tribe.uservoice.com/forums/195723-feature-ideas/suggestions/5605710--sold-out-only-x-positions-left-etc-type-label
and also first step of https://tribe.uservoice.com/forums/195723-feature-ideas/suggestions/13746300-to-get-stock-quantity-in-calender-view-and-add-to

**Comment by barryhughes** [comment]
Thanks for the PR, @masteradhoc!

This could definitely be useful for lots of users but - as is - I'm afraid we probably can't merge this PR.

* It assumes `Tribe__Tickets_Plus__Commerce__WooCommerce__Main` will be defined, but for many users who do not have Event Tickets Plus installed that will not be the case so we'd need some sort of safety check
* The approach used in [George's snippet](https://gist.github.com/ggwicz/bb71d468a8139b1918e830ea302bc7af) (using the `tribe_events_after_the_event_title` hook) is a nice one: if we stick to that approach and perhaps move this to either Event Tickets or Event Tickets Plus I think we'd be on track
* Following from the above, we'd possibly also wish to genericize things a bit so that, for example, RSVP and EDD users aren't left out in the cold
* I'm also a little concerned that despite the popularity of the UserVoice request there may also be users who do not wish to see the extra output on their list views, so I do wonder about making this optional

Overall though, this is a great idea and the above points don't take away from that. @borkweb - what are your thoughts - do you think we'd be happy to see this reworked as a fresh PR targeting ET+?

**Comment by masteradhoc** [comment]
any update here? @barryhughes :)

**Comment by barryhughes** [comment]
Sorry for the delay, @masteradhoc.

There's definitely quite a bit of demand for this functionality but we do feel it would be better if the code was relocated to Event Tickets (and/or Event Tickets Plus) and made a little more generic. 

With that in mind, we're going to log this for inclusion in an upcoming release and we'll plan on developing it internally: there are a few things we need to hash out in more detail and I'd hate for you to work on a further PR only to have to make significant changes once more.

Thanks again for the contribution and for pushing this forward. If you have any other questions let me know, otherwise I'll go ahead and close this PR.

**Comment by masteradhoc** [comment]
HI @barryhughes 
Thanks for the update.
I'll go ahead and close it, please include it in short timely manner. I have heard from many people that this for them would be a MUST for a great plugin like yours.

Thanks Brian

**Pull request closed without merging**
