### PR TITLE
Don't call remove_action in a function hooked to the same action

### PR DESCRIPTION
**Pull request by Chouby**
When calling remove_action in a function hooked to the same action, all functions hooked to this action with a lower priority are never called, thus breaking 3rd party plugins.

Fortunately, there is an easy way to achieve the same goal using a static variable as proposed in this PR. 

[#63474](https://central.tri.be/issues/63474)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Whitespace found at end of line | [Main.php:3047](https://github.com/moderntribe/the-events-calendar/blob/2d0726575c4b0b60490b55feef4ddfe11d4fe9c7/src/Tribe/Main.php#L3047)
:x: | Whitespace found at end of line | [Main.php:3049](https://github.com/moderntribe/the-events-calendar/blob/2d0726575c4b0b60490b55feef4ddfe11d4fe9c7/src/Tribe/Main.php#L3049)
:x: | Whitespace found at end of line | [Main.php:3054](https://github.com/moderntribe/the-events-calendar/blob/2d0726575c4b0b60490b55feef4ddfe11d4fe9c7/src/Tribe/Main.php#L3054)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
Thanks, @Chouby!

This looks solid - but bear with us a little longer so we can confirm it doesn't cause breakages elsewhere/during a run of the test suite and we'll look at merging it in :+1:

**Comment by barryhughes** [comment]
Ticket added: [#63474](https://central.tri.be/issues/63474)

**Comment by Chouby** [comment]
Thanks :)

**Comment by Chouby** [comment]
Hi,

I come back on this issue because the PR was indeed not merged (or wrongly merged) probably due to the code structure change: See https://github.com/moderntribe/the-events-calendar/blob/4.3.5/src/Tribe/Meta/Save.php#L113

It looks like https://github.com/moderntribe/the-events-calendar/commit/851eb9354eb98c099ca786e07198f8ee2eb6ca45 made for 4.2.5 reintroduced the issue.

**Pull request merged**
