### PR TITLE
Make the list view match the day view more closely.

### PR DESCRIPTION
**Pull request by Camwyn**
This makes the font colors match, aligns things the same way, as well as making the list view images resize the same as the day view images.

Ticket:
https://central.tri.be/issues/63599

**Related/Duplicates:**

Feature Image:
https://central.tri.be/issues/73822

Placement of padding (removed):
https://central.tri.be/issues/73421
https://central.tri.be/issues/63512

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [single-event.php:70](https://github.com/moderntribe/the-events-calendar/blob/1310d66d0bd8b83efb84299115450f076200a49c/src/views/list/single-event.php#L70)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
Looks good - unless added via a different PR, though, can we also add a changelog entry?

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [single-event.php:70](https://github.com/moderntribe/the-events-calendar/blob/b904cd285dd4fa57f8363d8957c7ada60574f8dd/src/views/list/single-event.php#L70)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
@Camwyn - remember to clear the `enhance` (or `question`) label so we know it's ready for a second look :+1:

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [single-event.php:70](https://github.com/moderntribe/the-events-calendar/blob/5752aaa449942fd75e0c9dfa8c87087c8fa921d2/src/views/list/single-event.php#L70)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [single-event.php:70](https://github.com/moderntribe/the-events-calendar/blob/bd428eebed496a9f6ebf45484d9b911fcc333d97/src/views/list/single-event.php#L70)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [single-event.php:70](https://github.com/moderntribe/the-events-calendar/blob/f8cc030b9c98d6e86f26b92609e95a44d1035d25/src/views/list/single-event.php#L70)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [single-event.php:70](https://github.com/moderntribe/the-events-calendar/blob/7df5b45be52629721b91ace83d8beace951e47d3/src/views/list/single-event.php#L70)

> via jenkins/codesniffer-phpcs

**Pull request merged**
