### PR TITLE
Add filter for changing category taxonomy labels.

### PR DESCRIPTION
**Pull request by kopepasah**
This would be useful (at least for me). :smiley:

### CODE REVIEW

**Comment by barryhughes** [comment]
@kopepasah:

Hey Koop! Sorry for the further delay here. After taking a fresh look I had some further thoughts on this one:

* It feels like `Tribe__Events__Events::generatePostTypeLabels()` might be a better home for this filter
* That would also let us add similar filters for each of the label arrays in that method (ie, for events, organizers and venues) which would be great for consistency

If you're still interested/in agreement, would you be able to rewrite in respect of the above?

**Comment by bordoni** [comment]
Hey @kopepasah, when you can take a look at this PR. Would love to get this in on the next release, or just let me know and I will re-create the PR with the required changes mentioned by @barryhughes above. :grin:

**Comment by kopepasah** [comment]
@bordoni I agree with @barryhughes, but my plate is extremely full right now and cannot make this commit for a couple months. My apologies.

**Comment by barryhughes** [comment]
We're taking this forward in a separate PR primarily because the codebase has changed significantly since this was first submitted.

Closing this one out, but thanks for the idea and feedback, @kopepasah - we'll drive it to conclusion in [PR/178](https://github.com/moderntribe/the-events-calendar/pull/178).

**Pull request closed without merging**
