### PR TITLE
TEC-2968 - fix hidden menu items when an event is password protected

### PR DESCRIPTION
**Pull request by jesseeproductions**
_Ref:_ [TEC-2968](https://moderntribe.atlassian.net/browse/TEC-2968)

This resolves an issue where the Menu is missing: https://cloudup.com/iouykOpX8hv

This fix brings it back: https://cloudup.com/ijIhe6E4vvB

I do not believe that coding is required ( but it could be ) For posts the title is visible on password protection: https://cloudup.com/iRMl9Oe8LNo

### CODE REVIEW

**Comment by paulmskim** [comment]
I don't know the original scope of the password-protected events, but did we not want the event title to render on password-protected events (else why would we have wanted to not return the title)? The code looks good, but just thought I'd pose this question.

**Review by lucatume — COMMENTED** [review]
On password-protected events, the post title should be hidden. I would refine that simple `__return_empty_string` into something that is taking the post, and hence the post type, as input and keep hiding the title of password-protected Events, Venues and Organizers.

**Comment by jesseeproductions** [comment]
That is fine about hiding the titles for our post types, but I would like to note WordPress shows the title for Password Protected posts:
Example in 2020: https://cloudup.com/iRMl9Oe8LNo

**Comment by Camwyn** [comment]
@jesseeproductions Should this be closed? The only change I'm seeing now is the readme.

**Comment by jesseeproductions** [comment]
> @jesseeproductions Should this be closed? The only change I'm seeing now is the readme.

Still in progress, put back in hold,

**Review by lucatume — APPROVED** [review]

**Pull request merged**
