### PR TITLE
Recurrence possible re-design

### PR DESCRIPTION
**Pull request by bordoni**
As per conversation with @zbtirrell and @leahkoerper, I've applied parts of the Mock from our new Designer on to recurrence.

screen shot 2016-12-24 at 05 43 17

_Rel:_ https://github.com/moderntribe/tribe-common/pull/307 https://github.com/moderntribe/events-pro/pull/539

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$events_label_singular_lowercase' | [events-meta-box.php:58](https://github.com/moderntribe/the-events-calendar/blob/e0f6e0c1862332f5303b9fa349b061fc966a1559/src/admin-views/events-meta-box.php#L58)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$events_label_plural_lowercase' | [events-meta-box.php:58](https://github.com/moderntribe/the-events-calendar/blob/e0f6e0c1862332f5303b9fa349b061fc966a1559/src/admin-views/events-meta-box.php#L58)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [events-meta-box.php:121](https://github.com/moderntribe/the-events-calendar/blob/e0f6e0c1862332f5303b9fa349b061fc966a1559/src/admin-views/events-meta-box.php#L121)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$events_label_singular_lowercase' | [events-meta-box.php:58](https://github.com/moderntribe/the-events-calendar/blob/e0f6e0c1862332f5303b9fa349b061fc966a1559/src/admin-views/events-meta-box.php#L58)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$events_label_plural_lowercase' | [events-meta-box.php:58](https://github.com/moderntribe/the-events-calendar/blob/e0f6e0c1862332f5303b9fa349b061fc966a1559/src/admin-views/events-meta-box.php#L58)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')' | [events-meta-box.php:121](https://github.com/moderntribe/the-events-calendar/blob/e0f6e0c1862332f5303b9fa349b061fc966a1559/src/admin-views/events-meta-box.php#L121)

> via jenkins/codesniffer-phpcs

**Comment by borkweb** [comment]
This looks good. Adding hold so it waits until the first MR after 4.4

**Comment by bordoni** [comment]
After a bunch of cleaning up, and work here I think it's good for a new Code Review. Do this with care, there is a lot of changes here.

**Comment by borkweb** [comment]
:+1:

**Pull request merged**
