### PR TITLE
97344 Add Test for append_timezone() Output

### PR DESCRIPTION
**Pull request by ggwicz**
**Ticket:** [**#97344**](http://central.tri.be/issues/97344)

**Code Review Note:** No readme entry for this change.

Luca guided me through creating this test, which I made to address the work we did this MR on [#97344](http://central.tri.be/issues/97344) (the PR for that work is in _Tribe Common_ over [here](https://github.com/moderntribe/tribe-common/pull/630)).

### CODE REVIEW

**Comment by barryhughes** [comment]
1. Not sure 100199 is the correct ticket number - should it be 97344?
2. When I think back to the problem described in 97344, the major problem was that we wouldn't necessarily show the correct abbreviation according to whether the event takes place while daylight savings time is in force, or not ... to really cover that, shouldn't our tests assess the timezone abbreviation at two different points in the year? Right now they only examine the abbreviation as it is in May.

**Comment by ggwicz** [comment]
Sorry Barry, my communication on this PR was confusing:
- This PR is not really meant to _actually_ fully test the bug of #97344 
- This PR is really just my saving progress/having the result of the Unit Testing meetings Luca did with me and Crisoforo today
- So the correct ticket is indeed #100199, as that's the ticket for those Unit Testing meetings
- And the purpose of this PR was just me creating a real, actual test

This test isn't a waste—it lays the groundwork for more nuance and DST testing, etc. But it's really just the result of the time Luca and I had together on the meeting this morning as a practice exercise of writing a test from scratch 👍

**Comment by lucatume** [comment]
tests all green again

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for **, but this was pull requested against *release/M18.04*.

**Comment by ggwicz** [comment]
Sorry for the confusion folks. I first put the ticket for this PR as 100199, which was a typo. I then changed it to the "correct" ticket, 100073, which is the ticket for Luca's Unit Testing meetings initiative—but since that ticket's target version is not `release/M18.04`, tr1b0t closed this PR.

So I've set the ticket to 97344, which is _sort of_ correct.

**Comment by barryhughes** [comment]
Going ahead and merging this (cc @ggwicz) ... we're hoping to package before too long so it seemed better to action asap.

**Pull request merged**
