### PR TITLE
make events-meta-box venue and organizer templates filterable

### PR DESCRIPTION
**Pull request by aaemnnosttv**
This pull request adds 2 filters to `admin-views/events-meta-box.php`.

They simply allow for the default venue and organizer template includes to be overridden, to allow for full control over their contents.

### CODE REVIEW

**Comment by zbtirrell** [comment]
would you mind pull requesting this (and the others you've generously provided) against `release/119`?  We are just packaging up `develop` for our next big release now.  We can more easily get this stuff merged into `release/119` for inclusion in the following release.  Thanks!

**Comment by aaemnnosttv** [comment]
Sure thing @zbtirrell, do I need to create a new PR for that? or I can modify the existing ones to point to the updated target branch?

**Comment by zbtirrell** [comment]
You may need to re-submit?  Updating would be fine if it will let you.

**Comment by aaemnnosttv** [comment]
@zbtirrell, above is the first resubmit of these against that release branch.  Then we can just close the ones that aren't going to be merged in the release.

**Comment by borkweb** [comment]
Half of this was adapted for `release/120`!  Thanks :+1:

https://github.com/moderntribe/the-events-calendar/pull/198

**Pull request closed without merging**
