### PR TITLE
add language switcher filter

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/67134

This PR adds a filter in the WPML integration to make sure archive links are still built in a way that makes sense.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Language_Switcher.php:15](https://github.com/moderntribe/the-events-calendar/blob/9f756939a68c8cbbfa1dcd00405c8b11ef3b7fd4/src/Tribe/Integrations/WPML/Language_Switcher.php#L15)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
Looks good to me 😄 ... should there be a changelog entry though?

**Comment by lucatume** [comment]
Changelog is in

**Comment by barryhughes** [comment]
⭐️

**Pull request merged**
