### PR TITLE
Feature/73866 ea client import messaging

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/73866

This PR:

* covers more places where we should use localized version of EA messages where available
* adds more EA + REST specific error messages
* adds a setting to limit the number of events imported from the source site and uses it to request that number at the most

Also note that I found out, during the tests, the non persistent cache would ignore user ID changes and alway return details for the first user, using the user ID in the cache key generation helps: https://github.com/moderntribe/the-events-calendar/pull/1303/files#diff-11b3f3a370885fc38177fe5c2798ce9fR1010

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space before the last parenthesis | [Abstract.php:130](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/Tribe/Aggregator/Tabs/Abstract.php#L130)
:x: | No space after opening parenthesis is prohibited | [Abstract.php:130](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/Tribe/Aggregator/Tabs/Abstract.php#L130)
:x: | There must be a single space after the first parenthesis | [Abstract.php:130](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/Tribe/Aggregator/Tabs/Abstract.php#L130)
:x: | There must be a single space after the first parenthesis | [Abstract.php:130](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/Tribe/Aggregator/Tabs/Abstract.php#L130)
:x: | There must be a single space before the last parenthesis | [Abstract.php:130](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/Tribe/Aggregator/Tabs/Abstract.php#L130)
:x: | No space before closing parenthesis is prohibited | [Abstract.php:130](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/Tribe/Aggregator/Tabs/Abstract.php#L130)
:x: | You must have a space after a closing parenthesis | [Abstract.php:130](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/Tribe/Aggregator/Tabs/Abstract.php#L130)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/34f172e5fce13e536fe2bcba0471efb189b223bb/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/048357b2f702f174ce072056d6e64818428e940b/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/048357b2f702f174ce072056d6e64818428e940b/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/efb60fc0ee8af611037241f9de534334fc453df9/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/efb60fc0ee8af611037241f9de534334fc453df9/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/ed7015224d38c7f2a8a6dd25bbe3a086c6839a32/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/ed7015224d38c7f2a8a6dd25bbe3a086c6839a32/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/829ac1f5e8764433668dc8bde38745db88d4625a/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/829ac1f5e8764433668dc8bde38745db88d4625a/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/81b767626af73a2b7411f2373315edb246b5e2f0/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/81b767626af73a2b7411f2373315edb246b5e2f0/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/c38959609d77935b9468f33612fef29168de4064/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/c38959609d77935b9468f33612fef29168de4064/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/66079733c2f6c786ea8f8329d1b4ab37db549cb2/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/66079733c2f6c786ea8f8329d1b4ab37db549cb2/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/c6b20f1edfc26a17c77dd808e4faad5f42801fd5/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/c6b20f1edfc26a17c77dd808e4faad5f42801fd5/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:103](https://github.com/moderntribe/the-events-calendar/blob/60f88452aa912988d5af5104dee884b75abb8d18/src/admin-views/aggregator/origins/url.php#L103)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/60f88452aa912988d5af5104dee884b75abb8d18/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Each line in an array declaration must end in a comma | [Settings.php:274](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Settings.php#L274)
:x: | Each line in an array declaration must end in a comma | [Settings.php:278](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Settings.php#L278)
:x: | Each line in an array declaration must end in a comma | [Settings.php:282](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Settings.php#L282)
:x: | Each line in an array declaration must end in a comma | [Settings.php:286](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Settings.php#L286)
:x: | Each line in an array declaration must end in a comma | [Settings.php:290](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Settings.php#L290)
:x: | Each line in an array declaration must end in a comma | [Settings.php:294](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Settings.php#L294)
:x: | Each line in an array declaration must end in a comma | [Settings.php:298](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Settings.php#L298)
:x: | Each line in an array declaration must end in a comma | [Settings.php:302](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Settings.php#L302)
:warning: | Comment refers to a TODO task &quot;scheduled imports starts&quot; | [Abstract.php:183](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/Tribe/Aggregator/Tabs/Abstract.php#L183)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:105](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/admin-views/aggregator/origins/url.php#L105)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/32636518786b60bc2c8d115acbac0ad8cc2718aa/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$field' | [url.php:105](https://github.com/moderntribe/the-events-calendar/blob/eaa747c9087f329c2ec165ac081f17075b32121b/src/admin-views/aggregator/origins/url.php#L105)
:warning: | Comment refers to a TODO task &quot;@luca set the correct URL for Knowledgebase here&quot; | [settings.php:399](https://github.com/moderntribe/the-events-calendar/blob/eaa747c9087f329c2ec165ac081f17075b32121b/src/admin-views/aggregator/settings.php#L399)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
This code is updated to use a date range in place of a count limit: ready for review.

**Comment by borkweb** [comment]
This looks pretty great! :+1:

**Pull request merged**
