### PR TITLE
Add organizer and venue by-slug endpoints plus tests

### PR DESCRIPTION
**Pull request by sc0ttkclark**
https://central.tri.be/issues/96088

### CODE REVIEW

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *TEC REST API*, but this was pull requested against *release/M18.01*.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *TEC REST API*, but this was pull requested against *release/M18.01*.

**Comment by barryhughes** [comment]
:christmas_tree:

**Comment by sc0ttkclark** [comment]
@barryhughes one last look/approve from you on this, thanks!

**Pull request merged**
