### PR TITLE
Prevent to add the virtual page to the Query

### PR DESCRIPTION
**Pull request by mitogh**
Ticket: https://central.tri.be/issues/97667

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space after the first parenthesis | [Query.php:477](https://github.com/moderntribe/the-events-calendar/blob/49046867c078729783e11ac35b6893f34d5e8852/src/Tribe/Query.php#L477)
:x: | There must be a single space before the last parenthesis | [Query.php:477](https://github.com/moderntribe/the-events-calendar/blob/49046867c078729783e11ac35b6893f34d5e8852/src/Tribe/Query.php#L477)

> via jenkins/codesniffer-phpcs

**Comment by mitogh** [comment]
Fixing of test would you mind take another look.

Thanks.

**Comment by bordoni** [comment]
Tests are still failing.

**Comment by mitogh** [comment]
Test passing again 💃

**Pull request merged**
