### PR TITLE
Update the`$query` object to reflect live previews from customizer

### PR DESCRIPTION
**Pull request by mitogh**
Ticket: https://central.tri.be/issues/100832

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Front_Page_View.php:92](https://github.com/moderntribe/the-events-calendar/blob/425a5ab64a480d5939ceff5d1d8eea3059a9e455/src/Tribe/Front_Page_View.php#L92)
:x: | There must be a single space before the last parenthesis | [Front_Page_View.php:98](https://github.com/moderntribe/the-events-calendar/blob/425a5ab64a480d5939ceff5d1d8eea3059a9e455/src/Tribe/Front_Page_View.php#L98)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Front_Page_View.php:92](https://github.com/moderntribe/the-events-calendar/blob/910927d3b8a7d4bcc06f770ef4a057ea099b7187/src/Tribe/Front_Page_View.php#L92)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Front_Page_View.php:93](https://github.com/moderntribe/the-events-calendar/blob/3bc8462c20c7d725922dbb6c36ed3989d8a74c25/src/Tribe/Front_Page_View.php#L93)
:x: | empty() and isset() must only contain variables (PHP 5.2 compatibility) | [Front_Page_View.php:117](https://github.com/moderntribe/the-events-calendar/blob/3bc8462c20c7d725922dbb6c36ed3989d8a74c25/src/Tribe/Front_Page_View.php#L117)

> via jenkins/codesniffer-phpcs

**Comment by mitogh** [comment]
Thank you for the feedback.

This one is ready for another round of eyes.

**Comment by mitogh** [comment]
This is coming from a QA repair the entry is already on the readme file.

**Comment by mitogh** [comment]
Closing this one an reopening a new PR with all the requested changes added to this PR.

Reason of the closing so we can merge this changes during the day.

**Pull request closed without merging**
