### PR TITLE
Fixed Spelling of Whethere to Whether

### PR DESCRIPTION
**Pull request by garrett-eclipse**

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Each line in an array declaration must end in a comma | [Event_Definition_Provider.php:158](https://github.com/moderntribe/the-events-calendar/blob/00d4d46253a0088d07a39673b51092c5fff0586e/src/Tribe/REST/V1/Documentation/Event_Definition_Provider.php#L158)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
Hi @garrett-eclipse - thanks for the PR! Can I ask you to sync your branch with `release/M17.10`?

**Comment by garrett-eclipse** [comment]
Hi @barryhughes I would be happy to. Can you guide me a little as I'm not 100% as to how to sync with a specific branch. Thank you

**Comment by barryhughes** [comment]
Apologies, @garrett-eclipse - no need. I was thrown by a change upstream. We're all good :-)

**Comment by garrett-eclipse** [comment]
Thanks @barryhughes - All the best

**Pull request merged**
