### PR TITLE
EA Client support for multiple organizers

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: https://central.tri.be/issues/94954

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space after the first square bracket | [Abstract.php:1556](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1556)
:x: | There must be a single space before the last square bracket | [Abstract.php:1556](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1556)
:x: | There must be a single space after the first square bracket | [Abstract.php:1559](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1559)
:x: | There must be a single space before the last square bracket | [Abstract.php:1559](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1559)
:x: | There must be a single space after the first square bracket | [Abstract.php:1561](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1561)
:x: | There must be a single space before the last square bracket | [Abstract.php:1561](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1561)
:x: | There must be a single space after the first square bracket | [Abstract.php:1564](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1564)
:x: | There must be a single space before the last square bracket | [Abstract.php:1564](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1564)
:x: | There must be a single space after the first square bracket | [Abstract.php:1565](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1565)
:x: | There must be a single space before the last square bracket | [Abstract.php:1565](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1565)
:x: | There must be a single space after the first square bracket | [Abstract.php:1568](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1568)
:x: | There must be a single space before the last square bracket | [Abstract.php:1568](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1568)
:x: | There must be a single space after the first square bracket | [Abstract.php:1569](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1569)
:x: | There must be a single space before the last square bracket | [Abstract.php:1569](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1569)
:x: | There must be a single space after the first square bracket | [Abstract.php:1846](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1846)
:x: | There must be a single space before the last square bracket | [Abstract.php:1846](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1846)
:x: | There must be a single space after the first square bracket | [Abstract.php:1849](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1849)
:x: | There must be a single space before the last square bracket | [Abstract.php:1849](https://github.com/moderntribe/the-events-calendar/blob/556ecbc6cf8aac9ce0eac86a02a5e1b45dc5b11a/src/Tribe/Aggregator/Record/Abstract.php#L1849)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *1.0.13*, but this was pull requested against *release/M17.25*.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space after the first square bracket | [Abstract.php:1556](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1556)
:x: | There must be a single space before the last square bracket | [Abstract.php:1556](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1556)
:x: | There must be a single space after the first square bracket | [Abstract.php:1559](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1559)
:x: | There must be a single space before the last square bracket | [Abstract.php:1559](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1559)
:x: | There must be a single space after the first square bracket | [Abstract.php:1561](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1561)
:x: | There must be a single space before the last square bracket | [Abstract.php:1561](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1561)
:x: | There must be a single space after the first square bracket | [Abstract.php:1564](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1564)
:x: | There must be a single space before the last square bracket | [Abstract.php:1564](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1564)
:x: | There must be a single space after the first square bracket | [Abstract.php:1565](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1565)
:x: | There must be a single space before the last square bracket | [Abstract.php:1565](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1565)
:x: | There must be a single space after the first square bracket | [Abstract.php:1568](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1568)
:x: | There must be a single space before the last square bracket | [Abstract.php:1568](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1568)
:x: | There must be a single space after the first square bracket | [Abstract.php:1569](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1569)
:x: | There must be a single space before the last square bracket | [Abstract.php:1569](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1569)
:x: | There must be a single space after the first square bracket | [Abstract.php:1846](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1846)
:x: | There must be a single space before the last square bracket | [Abstract.php:1846](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1846)
:x: | There must be a single space after the first square bracket | [Abstract.php:1849](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1849)
:x: | There must be a single space before the last square bracket | [Abstract.php:1849](https://github.com/moderntribe/the-events-calendar/blob/a181926bb43485fa8e9c3dfcd46a3f4c878b0804/src/Tribe/Aggregator/Record/Abstract.php#L1849)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
Are we merging this from `M17.24`?

**Pull request closed without merging**
