### PR TITLE
Dgwatkins master

### PR DESCRIPTION
**Pull request by lucatume**
I've updated the code to use the const for the taxonomy in place of the hardcoded string.

Ticket: [#80201](https://central.tri.be/issues/80201)

### CODE REVIEW

**Comment by zbtirrell** [comment]
Is there an associated ticket?

**Comment by lucatume** [comment]
No ticket for this; it's a small modification on this PR: https://github.com/moderntribe/the-events-calendar/pull/1382

**Comment by zbtirrell** [comment]
OK - can we at least get something in the Readme? 
Also - is F17.4 the right target branch?

**Comment by bordoni** [comment]
This should be pull requested at `master` with a `Needs Release` label.

**Comment by barryhughes** [comment]
Added a ticket ([#80201](https://central.tri.be/issues/80201)): this can ship in MR 17.11.

**Comment by bordoni** [comment]
👍

**Pull request merged**
