### PR TITLE
Strip single recurrence and `/all/` permalink logic from TEC (belongs in ECP)

### PR DESCRIPTION
**Pull request by barryhughes**
Removes permalink logic that ought to belong in PRO.

:ticket: [#74153](https://central.tri.be/issues/74153)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Recurring Events Restructure*, but this was pull requested against *release/M17.13*.

**Comment by barryhughes** [comment]
Re-opening: the ticket is in the _Recurring Events Restructure_ bucket, but the plan is to remove or replace the /all/ views at that point - we still need relief from this bug before then.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Recurring Events Restructure*, but this was pull requested against *release/M17.13*.

**Comment by barryhughes** [comment]
Re-opening for the reasons [noted here](https://github.com/moderntribe/the-events-calendar/pull/1453#issuecomment-312878411).

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Recurring Events Restructure*, but this was pull requested against *release/M17.13*.

**Pull request merged**
