### PR TITLE
Update the-events-calendar-fr_FR.po

### PR DESCRIPTION
**Pull request by Kcchouette**
Hello

Thank you for your project.

I don't find in the documentation where to update the translation files, so here some translated words for the french (FR) language.

### CODE REVIEW

**Comment by sebastienserre** [comment]
Hello @Kcchouette 
I'm one of the the responsable of French translation. Tis is done on translate here: https://translate.wordpress.org/projects/wp-plugins/the-events-calendar/stable/fr/default
you can easily join me on the frencjh WordPress Slack #traductions channel

**Comment by bordoni** [comment]
Thanks so much @sebastienserre for answering that question there.

**Comment by sebastienserre** [comment]
No problem, do not hesitate to ping me on French translation questions/matters

**Comment by Kcchouette** [comment]
@bordoni @sebastienserre It would be better to add this link on the README of this project.
Thank you!

**Comment by sebastienserre** [comment]
This is THE WordPress way of translation. Are you french @Kcchouette ?

**Comment by Kcchouette** [comment]
@sebastienserre yes

**Comment by sebastienserre** [comment]
alors vient:
wordpressfr.slack.com

**Pull request closed without merging**
