### PR TITLE
conditional Status/Category helper text for scheduled imports

### PR DESCRIPTION
**Pull request by zbtirrell**
See feedback doc

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$default_settings' | [import-form.php:173](https://github.com/moderntribe/the-events-calendar/blob/aa5cc1792cb116bf9567dd409594bcb9bb312c13/src/admin-views/aggregator/tabs/import-form.php#L173)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$default_settings' | [import-form.php:180](https://github.com/moderntribe/the-events-calendar/blob/aa5cc1792cb116bf9567dd409594bcb9bb312c13/src/admin-views/aggregator/tabs/import-form.php#L180)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$default_settings' | [import-form.php:187](https://github.com/moderntribe/the-events-calendar/blob/aa5cc1792cb116bf9567dd409594bcb9bb312c13/src/admin-views/aggregator/tabs/import-form.php#L187)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$default_settings' | [import-form.php:194](https://github.com/moderntribe/the-events-calendar/blob/aa5cc1792cb116bf9567dd409594bcb9bb312c13/src/admin-views/aggregator/tabs/import-form.php#L194)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$default_settings' | [import-form.php:200](https://github.com/moderntribe/the-events-calendar/blob/aa5cc1792cb116bf9567dd409594bcb9bb312c13/src/admin-views/aggregator/tabs/import-form.php#L200)
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$default_settings' | [import-form.php:206](https://github.com/moderntribe/the-events-calendar/blob/aa5cc1792cb116bf9567dd409594bcb9bb312c13/src/admin-views/aggregator/tabs/import-form.php#L206)

> via jenkins/codesniffer-phpcs

**Comment by borkweb** [comment]
This is miserable, but a cleaner solution would take a little bit more effort that isn't worth spending right now. :+1:

**Comment by zbtirrell** [comment]
Blame Leah.

**Comment by borkweb** [comment]
Always.

**Pull request merged**
