### PR TITLE
Feature/62704 add classes to single event meta labels

### PR DESCRIPTION
**Pull request by niconerd**
https://central.tri.be/issues/62704

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$website' | [venue.php:46](https://github.com/moderntribe/the-events-calendar/blob/d350c05cfc0aec108bba120dd62d4bb1afb833c3/src/views/modules/meta/venue.php#L46)

> via jenkins/codesniffer-phpcs

**Comment by juanfra** [comment]
I guess the `$website` var can contain the formatted link? If the answer is yes, then there's no need to sanitize that and skip the bot comment. If not, it's always a good practice to sanitize HTML before it's printed.

**Comment by niconerd** [comment]
Yeah, that's the formatted link. The URL for href attribute is escaped. I think we are good with that...

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$website' | [venue.php:46](https://github.com/moderntribe/the-events-calendar/blob/332883e01b2dd1ce8fa227017c95272d4a0bff41/src/views/modules/meta/venue.php#L46)

> via jenkins/codesniffer-phpcs

**Pull request merged**
