### PR TITLE
Add Sections for Core

### PR DESCRIPTION
**Pull request by bordoni**
_Ref:_ [C#67489](https://central.tri.be/issues/67489)

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $name is never used | [Day_List_View.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Day_List_View.php#L23)
:warning: | The method parameter $name is never used | [General_Theme.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/General_Theme.php#L23)
:warning: | The method parameter $name is never used | [Global_Elements.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Global_Elements.php#L23)
:warning: | The method parameter $name is never used | [Month_Week_View.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Month_Week_View.php#L23)
:warning: | The method parameter $name is never used | [Single_Event.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Single_Event.php#L23)
:warning: | The method parameter $name is never used | [Widget.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Widget.php#L23)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
:bangbang: This Pull Request is against a Central ticket for "Next Release". It shouldn't be merged until the Central ticket has been changed to "Current Release" or "CR Maintenance Release".

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | The method parameter $name is never used | [Day_List_View.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Day_List_View.php#L23)
:warning: | The method parameter $name is never used | [General_Theme.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/General_Theme.php#L23)
:warning: | The method parameter $name is never used | [Global_Elements.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Global_Elements.php#L23)
:warning: | The method parameter $name is never used | [Month_Week_View.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Month_Week_View.php#L23)
:warning: | The method parameter $name is never used | [Single_Event.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Single_Event.php#L23)
:warning: | The method parameter $name is never used | [Widget.php:23](https://github.com/moderntribe/the-events-calendar/blob/522e66314233ab864e7659d919359d251ef146b5/src/Tribe/Customizer/Widget.php#L23)

> via jenkins/codesniffer-phpcs

**Comment by lucatume** [comment]
👍

**Comment by borkweb** [comment]
The ticket this is associated seems to have gone away. Before we throw `merge` back on here, can you re-associate with a different Central ticket?

**Comment by bordoni** [comment]
Resolved @borkweb concerns.

**Pull request merged**
