### PR TITLE
Feature/recurrence

### PR DESCRIPTION
**Pull request by lucatume**
Still work in progress.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L100)
:x: | No space after opening parenthesis is prohibited | [Save.php:101](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L101)
:x: | There must be a single space after the first parenthesis | [Save.php:101](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L101)
:x: | There must be a single space after the first parenthesis | [Save.php:101](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L101)
:x: | There must be a space between elseif and the first parenthesis '(' | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space before the last parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | No space after opening parenthesis is prohibited | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space after the first parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space after the first parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space before the last parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space after the first parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space before the last parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | No space before closing parenthesis is prohibited | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space after the first parenthesis | [Save.php:153](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L153)
:x: | There must be a single space before the last parenthesis | [Save.php:153](https://github.com/moderntribe/the-events-calendar/blob/6025be1e8c15d9850d9958f7e3a096d22571bcb7/src/Tribe/Meta/Save.php#L153)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L100)
:x: | No space after opening parenthesis is prohibited | [Save.php:101](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L101)
:x: | There must be a single space after the first parenthesis | [Save.php:101](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L101)
:x: | There must be a single space after the first parenthesis | [Save.php:101](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L101)
:x: | There must be a space between elseif and the first parenthesis '(' | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space before the last parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | No space after opening parenthesis is prohibited | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space after the first parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space after the first parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space before the last parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space after the first parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space before the last parenthesis | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | No space before closing parenthesis is prohibited | [Save.php:112](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L112)
:x: | There must be a single space after the first parenthesis | [Save.php:153](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L153)
:x: | There must be a single space before the last parenthesis | [Save.php:153](https://github.com/moderntribe/the-events-calendar/blob/71b265b030d29c7a0c17f0283a5db2b61bb524ec/src/Tribe/Meta/Save.php#L153)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/e1bdde701353d3aa47be2a7ebe6ad6d694a81633/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/619e720be44ac0f6ee9a314f5160971b0980e516/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/5981ee348833b7e46d4010e30ab9e2560d63f29b/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/5bb644a543b92a5d92fad5920dd2fdbd06615a3c/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/c49224e762402e1a7d9550c655eafb4dd9353062/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/f5100bad9ef4b2a1ac7593260c663f60e2a96f28/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/0dc037ed37f8c5368c4770ea0f41d212e576adf5/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by borkweb** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/0dc037ed37f8c5368c4770ea0f41d212e576adf5/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/819c8b40e203eb076600bd9cf413ae0881cc8919/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/536b6f45cf0dd9188c44092b044d3961832e98c3/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/c00c50b791325a2e974a6938ecebb25d14fe5019/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/9089a25d0213d06fa70ec093d0cabe0de0f9256f/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/a6122cf974fb5e4cbbbba1f932d58d35d672c2bc/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/b671af8335996b9d449ad1f1d214f6c72935ae98/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task &quot;@luca add series related checks here&quot; | [Save.php:100](https://github.com/moderntribe/the-events-calendar/blob/3c95f4cfc85dc1cbad42d66022df0c980627711d/src/Tribe/Meta/Save.php#L100)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
Closed due to no longer been the way we want this to be merged into `master`

**Pull request closed without merging**
