### PR TITLE
⌗113541 Ensure "Enable JSON-LD" Widget Option Can be Unchecked

### PR DESCRIPTION
**Pull request by ggwicz**
**Ticket:** [**⌗113541**](http://central.tri.be/issues/113541)

**Code Review Note:** Sorry for some whitespace cleanup/churn here.

### CODE REVIEW

**Comment by jesseeproductions** [comment]
George, see what I did in this PR. I fixed the jsonld not being able to be saved on the first load of the widget as will as reduce the coding. It involved similar changes as well as some to the admin-widget template for each pro widget. 

https://github.com/moderntribe/events-pro/pull/1008

It would be nice to have the same coding in place for all the widgets.

**Comment by mitogh** [comment]
Just fixing conflicts on `readme` @ggwicz

**Comment by ggwicz** [comment]
@jesseeproductions Can you confirm that you're able to **un-check** the "Generate JSON-LD for Events" option in the PRO list widget with your code? Make sure to refresh the page after doing so and making sure the choice is respected. I pulled your branch and tried to do that but it would not let me un-check the option.

I _did_ rework the code here in this PR a bit though. The main thing I'm trying to solve for this ticket is:
1. The _Event List_ widget defaults to having the Generate JSON-LD option **checked**.
2. But if you **un-check** the option and save the widget, that is respected.

:point_up: #2 was not working here for a while, this PR fixes that. I could not get it to work using the approach in moderntribe/events-pro#1008

**Comment by ggwicz** [comment]
I've addressed readme conflicts and tweaked some of the code a bit, so this is ready for another review :mag_right

**Comment by jesseeproductions** [comment]
You are right. I tested again and all Pro widgets and found an issue with the Advanced List Widget, but all the others worked. Not sure why that one is not working.

**Pull request merged**
