### PR TITLE
#76297 | Fix Ability to Make Organizers or Venues Required for Community Events Submission

### PR DESCRIPTION
**Pull request by ggwicz**
_Ref:_ [C#76297](http://central.tri.be/issues/76297)

Related PR to Community Events → https://github.com/moderntribe/events-community/pull/255

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space before the last parenthesis | [create-venue-fields.php:23](https://github.com/moderntribe/the-events-calendar/blob/2c8abd16638a3a34ad6ef74c606b228e38046b09/src/admin-views/create-venue-fields.php#L23)

> via jenkins/codesniffer-phpcs

**Comment by barryhughes** [comment]
This may be fine but I notice we're not doing anything with `$_VenueState` - deliberate or oversight?

**Comment by barryhughes** [comment]
...When the time comes for QA let's be sure to ask them to test on both sides (admin and frontend editors) :white_check_mark:

**Comment by ggwicz** [comment]
@barryhughes:

> This may be fine but I notice we're not doing anything with $_VenueState - deliberate or oversight?

Deliberate — I did not encounter the PHP notice with the $_VenueState field or the other geo- fields.

**Pull request merged**
