### PR TITLE
Implement a new "Imports" settings tab for Event Aggregator

### PR DESCRIPTION
**Pull request by borkweb**
See:

* https://central.tri.be/issues/61235
* https://central.tri.be/issues/61239
* https://central.tri.be/issues/61194
* https://central.tri.be/issues/61195

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space before the last parenthesis | [settings.php:37](https://github.com/moderntribe/the-events-calendar/blob/8eef0e08ed7d6d6c638425f7f72014d3aaac78d4/src/admin-views/aggregator/settings.php#L37)
:x: | There must be a single space before the last parenthesis | [settings.php:37](https://github.com/moderntribe/the-events-calendar/blob/8eef0e08ed7d6d6c638425f7f72014d3aaac78d4/src/admin-views/aggregator/settings.php#L37)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Event.php:3](https://github.com/moderntribe/the-events-calendar/blob/98d120c404070f3d8672e2a46221e7398f02081c/src/Tribe/Aggregator/Event.php#L3)
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Settings.php:3](https://github.com/moderntribe/the-events-calendar/blob/98d120c404070f3d8672e2a46221e7398f02081c/src/Tribe/Aggregator/Settings.php#L3)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
💯

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Event.php:3](https://github.com/moderntribe/the-events-calendar/blob/98d120c404070f3d8672e2a46221e7398f02081c/src/Tribe/Aggregator/Event.php#L3)
:x: | Logical operator &quot;or&quot; is prohibited; use &quot;||&quot; instead | [Settings.php:3](https://github.com/moderntribe/the-events-calendar/blob/98d120c404070f3d8672e2a46221e7398f02081c/src/Tribe/Aggregator/Settings.php#L3)

> via jenkins/codesniffer-phpcs

**Pull request merged**
