### PR TITLE
Fix/96938 single post dropdown not hard code organizer

### PR DESCRIPTION
**Pull request by cliffordp**
https://central.tri.be/issues/96938

### CODE REVIEW

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *M18.02*, but this was pull requested against *release/M18.01*.

**Comment by bordoni** [comment]
Moved it back into `master` until `M18.02` is created.

**Comment by cliffordp** [comment]
@barryhughes please code review now that 18.02 is the base branch. tyvm.

**Comment by cliffordp** [comment]
Thanks @bordoni !

**Pull request merged**
