### PR TITLE
is_embed fix for older versions of WordPress

### PR DESCRIPTION
**Pull request by jesseeproductions**
_Ref:_ [C#62577](https://central.tri.be/issues/62577) - We use is_embed 4 different times in this template: the-events-calendar/src/Tribe/Templates.php 

Instead of wrapping those with a version check I added one to the general.php file 

Not sure if this is the best approach, but this would help prevent fatals in WordPress 3.9 to WordPress 4.3

Method for commit is in common: https://github.com/moderntribe/tribe-common/pull/108

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a space between if and the first parenthesis '(' | [general.php:1543](https://github.com/moderntribe/the-events-calendar/blob/2bc0b3ee5b2e4c715dd95730a029408d5dcc1561/src/functions/template-tags/general.php#L1543)
:x: | Opening brace must be the last content on the line | [general.php:1545](https://github.com/moderntribe/the-events-calendar/blob/2bc0b3ee5b2e4c715dd95730a029408d5dcc1561/src/functions/template-tags/general.php#L1545)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
This could be problematic, lets say that someone else does the same, but having the return be true? I mean I would rather make a wrapper for the function and do all the required checks.

**Comment by jesseeproductions** [comment]
No problem, but I am not sure what you are looking for can you explain or give an example?

**Comment by bordoni** [comment]
I mean, having a method that checks for the version + if doesn't function exists and if both are true then we use `is_embed`. Use that method instead of using `is_embed`.

**Comment by zbtirrell** [comment]
I'm actually OK with this approach. @borkweb what do you think?

**Comment by barryhughes** [comment]
Tagging `enhance` - looks like work is still in progress here (ie, moving to using new method `Tribe__Templates::is_embed()`).

**Comment by borkweb** [comment]
🚆

**Pull request merged**
