### PR TITLE
Making sure that wp_query is not empty to prevent potential fatals from occurring

### PR DESCRIPTION
**Pull request by archetypalsxe**
I keep getting a fatal when using this plugin from this file. Adding a check to make sure that the object is not empty before actually attempting to use

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | ! must be followed by a single space | [general.php:1694](https://github.com/moderntribe/the-events-calendar/blob/29409bee5b24bb9a428cb4ef10f97bb0846193dd/src/functions/template-tags/general.php#L1694)
:x: | There must be a single space after the first parenthesis | [general.php:1694](https://github.com/moderntribe/the-events-calendar/blob/29409bee5b24bb9a428cb4ef10f97bb0846193dd/src/functions/template-tags/general.php#L1694)
:x: | There must be a single space before the last parenthesis | [general.php:1694](https://github.com/moderntribe/the-events-calendar/blob/29409bee5b24bb9a428cb4ef10f97bb0846193dd/src/functions/template-tags/general.php#L1694)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
@barryhughes can we make sure to include this on the next MR?

**Comment by ggwicz** [comment]
I'll get this one into M18.04!

**Comment by ggwicz** [comment]
Hey @archetypalsxe,

We talked about this issue internally a bit, and have decided to address this throughout our plugins as a whole—not just the specific line you fixed in this PR.

For now, we have submitted changes based on your change to the following plugins, with the corresponding Pull Requests linked below:
- _The Events Calendar:_ https://github.com/moderntribe/the-events-calendar/pull/1841
- _Tribe Common:_ https://github.com/moderntribe/tribe-common/pull/628
- _Events Calendar PRO:_ https://github.com/moderntribe/events-pro/pull/801

We've been sure to give you props in each plugin—thanks for this contribution!

**Comment by archetypalsxe** [comment]
Thanks, it's appreciated!

**Pull request closed without merging**
