### PR TITLE
Support Tribe_Error messages in get_service_message()

### PR DESCRIPTION
**Pull request by sc0ttkclark**
https://central.tri.be/issues/107606

### CODE REVIEW

**Comment by bordoni** [comment]
Why `master` here? Should we push to `release/M18.09`?

**Comment by sc0ttkclark** [comment]
I don't want this to hold off any ongoing release, it can go into the next one.

**Comment by bordoni** [comment]
We just started `18.09` so that is good.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for **, but this was pull requested against *release/M18.09*.

**Comment by bordoni** [comment]
Lets get a changelog in.

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for **, but this was pull requested against *release/M18.09*.

**Comment by sc0ttkclark** [comment]
Added changelog

**Pull request merged**
