### PR TITLE
Fix/broken tests

### PR DESCRIPTION
**Pull request by lucatume**
Ticket: n/a
This PR restores the Travis CI tests and fixes the code that was creating the issue.

A remake of PR https://github.com/moderntribe/the-events-calendar/pull/1754

### CODE REVIEW

**Comment by tr1b0t** [comment]
Closing this Pull Request because it is pull requested against the wrong branch. The Central ticket is for *Ticket Editor*, but this was pull requested against *release/M18.02*.

**Comment by lucatume** [comment]
This is on hold until code from M18.01 has been merged into 18.02.

**Comment by lucatume** [comment]
Now that the code is merged this is ready for a look.

**Comment by borkweb** [comment]
Should there be a changelog entry?

**Comment by lucatume** [comment]
I've really just fixed stuff that was supposed to work already and quite remote; I'd say no.

**Pull request merged**
