### PR TITLE
Remove script type attribute

### PR DESCRIPTION
**Pull request by stian-overasen**
The “type” attribute is unnecessary for JavaScript resources.

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$eventsOptions' | [Options_Exception.php:19](https://github.com/moderntribe/the-events-calendar/blob/6942abd563aa08e0fa06d1bdc615cd9741e380eb/src/Tribe/Options_Exception.php#L19)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
I would like to know if there is any reason why would be better to not have the `type`?

**Comment by ggwicz** [comment]
From Mozilla Docs:
> HTML5 specification urges authors to omit the attribute rather than provide a redundant MIME type.

The `type` attribute is not _deprecated_, so we don't **have to** remove this attribute. But we don't need it, since we're not specifying any other "kind" of JavaScript than just the generic JavaScript in modern browsers, and so I would vote for removing it. Happy to take ownership of this change and advance it.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$eventsOptions' | [Options_Exception.php:19](https://github.com/moderntribe/the-events-calendar/blob/3b871f167abb2e0106eae1a7770cc807c87be7aa/src/Tribe/Options_Exception.php#L19)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$eventsOptions' | [Options_Exception.php:19](https://github.com/moderntribe/the-events-calendar/blob/87a55871048e683297a6e1388cf7e47bc0916cdf/src/Tribe/Options_Exception.php#L19)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
**Ticket:** [**#100944**](http://central.tri.be/issues/100944)

**Pull request merged**
