### PR TITLE
Add event category taxonomy args filter

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Add tribe_events_register_event_cat_type_args filter and document both filters used in Main::registerPostType().

Needed for me to be able to move forward with:

* https://central.tri.be/issues/80267
* https://central.tri.be/issues/80268

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | Whitespace found at end of line | [Main.php:1585](https://github.com/moderntribe/the-events-calendar/blob/ae68a71b9dcc9bdea9f93223cadaa4d790450b71/src/Tribe/Main.php#L1585)
:x: | Whitespace found at end of line | [Main.php:1604](https://github.com/moderntribe/the-events-calendar/blob/ae68a71b9dcc9bdea9f93223cadaa4d790450b71/src/Tribe/Main.php#L1604)

> via jenkins/codesniffer-phpcs

**Comment by bordoni** [comment]
Once this has a Given release branch it's good for a merge.

**Comment by sc0ttkclark** [comment]
👏 Thanks!

**Comment by barryhughes** [comment]
Hey @sc0ttkclark!

* Though `release/M17.11` is up-to-date with `master` there's something slightly funky with this merge if you look at the version # changes etc
* Needs a changelog entry (whether one for both issues or two separate ones)

**Comment by barryhughes** [comment]
Ready for another look.

Ticket added: :ticket: [#80658](https://central.tri.be/issues/80658)

**Comment by zbtirrell** [comment]
:shipit:

**Comment by sc0ttkclark** [comment]
👏

**Pull request merged**
