### PR TITLE
fix(timezone notice): The timezone notice responds incorrectly.

### PR DESCRIPTION
**Pull request by Camwyn**
The timezone notice appears to respond incorrectly when on an event edit page (admin). The function checks the event timezone properly, but when the notice is set, it uses the site timezone. This is all well and good until we're using "manual timezones for each event" - in which case the site timezone is fine but the event one is not (defaults to UTC+0).

Then we get messages like "...and avoid using a UTC timezone offset such as “America/Los_Angeles”. This just confuses folks.

Proposed fix: store the timezone string when we check it and reuse it in the notice.

📷 (good): http://p.tri.be/2lwzwW
📷 (good): http://p.tri.be/Vk0q4A
📷 (bad): http://p.tri.be/SoGWi9

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
I like this solution

**Comment by Camwyn** [comment]
@bordoni what happened here (closed with no explanation)?

**Comment by sc0ttkclark** [comment]
This probably auto-closed because B19.12 branch was deleted.

**Comment by bordoni** [comment]
Sorry branch deleted, can we move it to B19.13?

**Pull request closed without merging**
