### PR TITLE
Prevent loading of an Activation hook when outdate Common

### PR DESCRIPTION
**Pull request by bordoni**
When we are activating The Events Calendar and we have an outdated version of Common we need to make sure we are not triggering the activation hook of The Events Calendar, because it could lead into fatals due to older version of Common been loaded first.

The implementation here delays that Activation trigger to another request, so it can have the latest Common loaded via normal common-lib version comparing.

📹 http://i.bordoni.me/b9d029f2e388

### CODE REVIEW

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [Main.php:450](https://github.com/moderntribe/the-events-calendar/blob/6cc751b392f8340a82cd217dc21d0919a07a1744/src/Tribe/Main.php#L450)

> via jenkins/codesniffer-phpcs

**Comment by borkweb** [comment]
This looks pretty good! I'd love to see a screencast of this in action and functional with the known fail-case.

**Comment by bordoni** [comment]
_Recording_

**Comment by mitogh** [comment]
👍 solid!

**Pull request merged**
