### PR TITLE
Deprecate public method that's unused in our codebase

### PR DESCRIPTION
**Pull request by jazbek**
Searched for this method throughout the codebase, we're not using it. Also seems unnecessary. Deprecating instead of removing because it's public.

Internal Ref: https://central.tri.be/issues/28005

### CODE REVIEW

**Comment by bordoni** [comment]
Should we add what version we will remove this?

**Comment by jazbek** [comment]
Sure, I guess I am not 100% sure of the upcoming version numbers though... @zbtirrell?

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space after the first parenthesis | [Main.php:3475](https://github.com/moderntribe/the-events-calendar/blob/b131a317ed7c274c8a36e8b7806375ea6cbe7094/src/Tribe/Main.php#L3475)
:x: | There must be a single space before the last parenthesis | [Main.php:3475](https://github.com/moderntribe/the-events-calendar/blob/b131a317ed7c274c8a36e8b7806375ea6cbe7094/src/Tribe/Main.php#L3475)

> via jenkins/codesniffer-phpcs

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:x: | There must be a single space after the first parenthesis | [Main.php:3475](https://github.com/moderntribe/the-events-calendar/blob/b131a317ed7c274c8a36e8b7806375ea6cbe7094/src/Tribe/Main.php#L3475)
:x: | There must be a single space before the last parenthesis | [Main.php:3475](https://github.com/moderntribe/the-events-calendar/blob/b131a317ed7c274c8a36e8b7806375ea6cbe7094/src/Tribe/Main.php#L3475)

> via jenkins/codesniffer-phpcs

**Comment by zbtirrell** [comment]
Let's go with `4.5`.  That should give customizers a reasonable period of time to tweak their mods.

**Comment by tr1b0t** [comment]
Status|Message|Line
:-----:|-----|-----
:warning: | Comment refers to a TODO task | [Main.php:3472](https://github.com/moderntribe/the-events-calendar/blob/8de7876d562d5f7ba07ce7593dc25232ac948789/src/Tribe/Main.php#L3472)

> via jenkins/codesniffer-phpcs

**Comment by borkweb** [comment]
:+1:

**Pull request merged**
