### PR TITLE
Remove extra trailing quotes

### PR DESCRIPTION
**Pull request by Camwyn**
Ticket: https://central.tri.be/issues/85603

removes the extra trailing quotes at the ends of 2 lines

### CODE REVIEW

**Comment by borkweb** [comment]
Add a changelog entry to `readme.txt` and change the base branch to `release/M17.16`

**Comment by Camwyn** [comment]
According to the ticket, this is slated for 17.17 - and there isn't a bucket for that yet. Holding for then?

**Comment by ggwicz** [comment]
Once conflicts are resolved this should be ready for another approval and can merge.

**Comment by Camwyn** [comment]
Should be all set!

**Pull request merged**
