### PR TITLE
Show Event Views in Mobile Devices - Twenty Fourteen

### PR DESCRIPTION
**Pull request by jesseeproductions**
Fixes a conflict on mobile devices in Twenty Fourteen where the Event
Views (month, List, Etc) are hidden from some css in the theme

### CODE REVIEW

**Comment by bordoni** [comment]
Wait what? What was the change here?

**Comment by jesseeproductions** [comment]
Added CSS, sorry it was missing. 

This fixes and issue in Twenty Fourteen with the Event Views of Month, List, etc, not showing in screen sizes smaller then 400px.

**Comment by borkweb** [comment]
Can you send in another commit with the CSS compiled again?

**Comment by borkweb** [comment]
This is good for a merge!

**Pull request merged**
