### PR TITLE
Update common.

### PR DESCRIPTION
**Pull request by Camwyn**
Pull in latest B20.11 version of common.

### CODE REVIEW

**Review by borkweb — COMMENTED** [review]
Shouldn't this be using the [latest tribe-common hash](https://github.com/moderntribe/tribe-common/commits/release/B20.11) for `release/B20.11`, `5e8909e`?

**Comment by Camwyn** [comment]
> Shouldn't this be using the [latest tribe-common hash](https://github.com/moderntribe/tribe-common/commits/release/B20.11) for `release/B20.11`, `5e8909e`?

It is? At least it appears to be if you [check the changed files](https://github.com/moderntribe/tribe-common/compare/dbb01fbde953877f2749e7f2b2d0320c300e2962...5e8909efd3be2696a7a979df18c0a63c1cf9e22c#diff-51d712594f61a2fcdfe1bfc02ddaa68f3bbd787a79d01fc2e6a2bcb906c9b71a)?

**Comment by borkweb** [comment]
Ha...I'm an idiot. Thank you for clearing that up for me :+1:

**Comment by Camwyn** [comment]
Bot just updated ~20 minutes ago - should there still be differences?
hm, this looks well behind current: https://github.com/moderntribe/tribe-common/commit/6c4834f53c5194f93e7b24f0578395c32638d6b4

**Comment by lucatume** [comment]
I've fixed the issue, [in Common](https://github.com/moderntribe/tribe-common/pull/1483), that was causing this.
I'm waiting for the tests to pass on this to make sure the fix is actually correct.

**Comment by lucatume** [comment]
[Common PR](https://github.com/moderntribe/tribe-common/pull/1483) passed, I've updated the branch and will wait for tests to pass.

**Review by borkweb — APPROVED** [review]
:+1:

**Comment by borkweb** [comment]
Looks glorious. I'm merging it!

**Comment by lucatume** [comment]
> Looks glorious. I'm merging it!

Thanks.

**Pull request merged**
