### PR TITLE
Changed admin events view custom_columns

### PR DESCRIPTION
**Pull request by kittsville**
Replaced unnecessary conditionals in method custom_columns with a switch; resulting code is
easier to read and more efficient.

### CODE REVIEW

**Comment by afragen** [comment]
Check class name. Needs to be `Tribe__Events__Events`

**Comment by kittsville** [comment]
Sorry about that, I shouldn't have broken the golden rule and committed without testing. Working fine now.

**Comment by afragen** [comment]
😊

**Comment by kittsville** [comment]
I've made other changes to the class including a feature addition and some refactoring. So, given that and the major restructuring that's happens to tribe events since I'll just close this and re-pull with those changes but without the merge conflicts.

**Pull request closed without merging**
