### PR TITLE
Remove the Duplication

### PR DESCRIPTION
**Pull request by bordoni**
_Ref:_ [C#42572](https://central.tri.be/issues/42572)

### CODE REVIEW

**Comment by barryhughes** [comment]
Hey man, I see from the ticket the problem was showing up in the context of the CE submission form and possibly other related pages - but if we merge this change it will kill any before/after HTML on regular event pages when the Default Event Template is in use.

**Comment by bordoni** [comment]
Yeah... You are right, looking at that.

**Comment by bordoni** [comment]
I removed the lines, now this became a _hotfix_, but it's worth merging. It was throwing a notice.

**Comment by borkweb** [comment]
:+1:

**Pull request merged**
